### ISSUE TITLE
How can I download this checkpoint

### ISSUE THREAD

**Issue by dhyaaalayed** [reedscot/icml2016#25]
this file is missing I didn't find it: coco_gru18_bs64_cls0.5_ngf128_ndf128_a10_c512_80_net_T.t7

when I run this script: ./scripts/demo_coco.sh
 I got this error:
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so{
  gpu : 1
  filenames : ""
  queries : "scripts/coco_queries.txt"
  noisemode : "random"
  dataset : "coco"
  noisetype : "normal"
  batchSize : 16
  net_txt : "/home/reedscot/checkpoints/coco_gru18_bs64_cls0.5_ngf128_ndf128_a10_c512_80_net_T.t7"
  imsize : 1
  net_gen : "coco_fast_t70_nc3_nt128_nz100_bs64_cls0.5_ngf196_ndf196_100_net_G.t7"
  nz : 100
  checkpoint_dir : "/home/reedscot/checkpoints"
  doc_length : 201
  display : 0
}
/home/dieaa/torch/install/bin/luajit: cannot open </home/reedscot/checkpoints/coco_gru18_bs64_cls0.5_ngf128_ndf128_a10_c512_80_net_T.t7> in mode r  at /home/dieaa/t
orch/pkg/torch/lib/TH/THDiskFile.c:673
stack traceback:
        [C]: at 0x7f29b3ea2440
        [C]: in function 'DiskFile'
        /home/dieaa/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
        txt2img_demo.lua:44: in main chunk
        [C]: in function 'dofile'
        ...ieaa/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00405d50

**Comment by fenglinlie** [comment]
i used the pretrained models and got the same error.i changed the path of model and text encoder to absolute path and it worked

**Comment by ghost** [comment]
What does that mean
